"""empty message

Revision ID: 1175f217b4a4
Revises: 
Create Date: 2020-11-10 00:17:57.929999

"""
from alembic import op
import sqlalchemy as sa

from datetime import datetime
import csv


# revision identifiers, used by Alembic.
revision = '1175f217b4a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('year_month', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(), nullable=False),
    sa.Column('edition', sa.BigInteger(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table')
    )
    op.create_table('feed_backs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('user_text', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('futures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secid', sa.String(), nullable=True),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('lasttradedate', sa.DateTime(), nullable=True),
    sa.Column('assetcode', sa.String(), nullable=True),
    sa.Column('prevopenposition', sa.BigInteger(), nullable=True),
    sa.Column('prevsettleprice', sa.Float(), nullable=True),
    sa.Column('oi_rub', sa.Float(), nullable=True),
    sa.Column('oi_percentage', sa.Float(), nullable=True),
    sa.Column('lasttrademonth', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secid', sa.String(), nullable=True),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('lasttradedate', sa.DateTime(), nullable=True),
    sa.Column('assetcode', sa.String(), nullable=True),
    sa.Column('prevopenposition', sa.BigInteger(), nullable=True),
    sa.Column('prevsettleprice', sa.Float(), nullable=True),
    sa.Column('oi_rub', sa.Float(), nullable=True),
    sa.Column('oi_percentage', sa.Float(), nullable=True),
    sa.Column('lasttrademonth', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('underlying_future', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('underlyings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('exp_clearing', sa.String(), nullable=True),
    sa.Column('exp_type', sa.String(), nullable=True),
    sa.Column('web_page', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying')
    )
    # ### end Alembic commands ###
    ##### получаем данные из csv файла
    with open('data/underlying.csv', encoding='utf-8') as f:
        lst_data = list(csv.reader(f))

    ##### добавляем данные в БД
    underlyings_table = sa.table('underlyings',
                             sa.Column('id', sa.Integer()),
                             sa.Column('underlying', sa.String()),
                             sa.Column('name', sa.String()),
                             sa.Column('section_id', sa.Integer()),
                             sa.Column('section', sa.String()),
                             sa.Column('quote', sa.String()),
                             sa.Column('exp_clearing', sa.String()),
                             sa.Column('exp_type', sa.String()),
                             sa.Column('web_page', sa.Text()),
                             sa.Column('date_created', sa.DateTime()))

    lst_underlyings = []
    for i, t in enumerate(lst_data[1:]):
        lst_underlyings.append({'id': i+1, 'underlying': t[0], 'name': t[1],
                             'section_id': t[2], 'section': t[3], 'quote': t[4],
                             'exp_clearing': t[5], 'exp_type': t[6], 'web_page': t[7],
                             'date_created': datetime.utcnow()})

    op.bulk_insert(underlyings_table, lst_underlyings)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('underlyings')
    op.drop_table('options')
    op.drop_table('futures')
    op.drop_table('feed_backs')
    op.drop_table('editions')
    op.drop_table('cells')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
